<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>f3dat</string>
		<string>dat</string>
		<string>f3fis</string>
		<string>fis</string>
	</array>
	<key>name</key>
	<string>Itasca FLAC</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(?i:(\d+\.\d*(e[\-\+]?\d+)?))(?=[^a-zA-Z_])</string>
			<key>name</key>
			<string>constant.numeric.float.f3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(\d+e[\-\+]?\d+))</string>
			<key>name</key>
			<string>constant.numeric.float.f3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([1-9]+[0-9]*|0)</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.f3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\b(call|clean|cyc|cycle|expgrid|impgrid|new|pause|quit|rest|restore|ret|return|sav|save|set|solve|title)\b</string>
			<key>name</key>
			<string>constant.language.f3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\b(apply|attach|delete|error|fix|free|geometry|group|hist|history|ini|initial|int|interface|list|local|model|plot|prop|step|system|water)\b\s+</string>
			<key>name</key>
			<string>constant.language.f3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*\b(gen|generate)\b\s*\b(zone)?\b\s*\b(copy|merge|reflect|separate)?\b</string>
			<key>name</key>
			<string>constant.language.f3dats</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(range)\b\s+</string>
			<key>name</key>
			<string>constant.language.f3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(add|bitmap|brick|britt|brittle|bulk|center|coh|cylinder|cyl|dd|delete|dens|densify|dila|dip|disp|dvel|elastic|end1|end2|export|extra|face|fish|fishcall|fric|geom_rep|gpextra|gp|gradient|group|hist_rep|id|internal|key|kn|ks|large|maxedge|model|mohr|name|normal|nstep|nstress|nvel|plane|orientation|origin|poiss|prop|radius|ratio|remove|shear|size|slot|smalldisp|small|sphere|state|strainsoftening|sxx|syy|szz|tens|tol|ttab|unbal|vel|x|y|young|z|zone)\b</string>
			<key>name</key>
			<string>variable.parameter.type.f3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(case_of|caseof|Case_of|Caseof|case|Case|end_case|command|end_command|end|if|else|else if|end_if|exit|loop|while|foreach|end_loop|section|end_section)\b</string>
			<key>name</key>
			<string>keyword.language.f3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*&amp;\s*$\n?</string>
			<key>name</key>
			<string>keyword.language.f3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*(=|\*|\+|\^|\-|\/|\#|\,)\s*</string>
			<key>name</key>
			<string>keyword.operator.f3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\s*(math|abs|acos|and|asin|atan|atan2|cos|degrad|exp|grand|ln|log|unit)\b</string>
			<key>name</key>
			<string>storage.type.function.f3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\s*(dot|error|float|int|mag|max|min|not|null|or|pi|round|sgn|sin|sqrt|tan|union|urand|vector|xcomp|ycomp|zcomp)\b</string>
			<key>name</key>
			<string>storage.type.function.f3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((;)(?!\{).*$\n?)</string>
			<key>name</key>
			<string>comment.language.f3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*(&lt;|=&lt;|&gt;|&gt;=|#)\s*</string>
			<key>name</key>
			<string>keyword.operator.comparison.f3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((\'|\")[a-zA-Z,0-9,_,\s,\.,\,,/,\-,\*,:,=,!]*(\'|\"))</string>
			<key>name</key>
			<string>string.language.f3dat</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\[|\])</string>
			<key>name</key>
			<string>storage.type.function.f3dat</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.f3dat</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.f3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\@\w+)\(?([a-zA-Z0-9,\.,_]*)\)?\s*</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.language.f3dat</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.f3dat</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.f3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(define|def)\s*([\w+_]+)\s*\(?([a-zA-Z0-9,_]*)\)?\s*$\n?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.f3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(array|array_dim|array_size|buildstr|del_table|get_array|get_mem|lose_mem|mem|open|out|parse|read|strlen|string|substr|write|table|table_size|xtable|ytable)\(</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(at_list|close|find_zone|i_elem_list|i_find|i_node_head|i_node_list|gp_head|gp_list|out|gravity|grav|xgrav|ygrav|zgrav|zone_head|z_list)\b\s*</string>
			<key>name</key>
			<string>entity.name.function.f3dat</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.f3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(at_master|at_qweight|at_slave|at_type|at_weight)\(</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.f3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(gp_disp|gp_extra|gp_funbal|gp_group|gp_linkindex|gp_linkzone|gp_near|gp_next|gp_pos|gp_removegroup|gp_xdisp|gp_xfunbal|gp_xload|gp_xpos|gp_ydisp|gp_yfunbal|gp_yload|gp_ypos|gp_zdisp|gp_zfunbal|gp_zload|gp_zpos|gp_zvel)\(</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.f3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(z_cen|z_density|z_extra|z_facegp|z_faceremovegroup|z_facegroup|z_facenorm|z_find|z_group|z_id|z_join|z_linkindex|z_linkzone|z_model|z_next|z_pp|z_prop|z_volume|z_xcen|z_ycen|z_zcen)\(</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.f3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(z_fsi|z_gp|z_near|z_sig1|z_sig2|z_sig3|z_state|z_sxx|z_sxy|z_sxz|z_syy|z_syz|z_szz)\(</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.f3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(ie_zhost|ie_vert|ie_norm|ie_area|in_area|in_disp|in_extra|in_ftarget|in_id|in_next|in_nstr|in_pos|in_ztarget)\(</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.f3dat</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(uds_create|uds_group|uds_near|uds_pos|uds_value)\(</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.f3dat</string>
	<key>uuid</key>
	<string>a4358a63-d396-4e0c-9b3d-f0de59021e43</string>
</dict>
</plist>
